name: Master CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install Dependencies
        run: yarn install --cwd ./functions
      - name: deploy
        uses: w9jds/firebase-action@v1.0.1
        if: success()
        with:
          args: deploy --only functions
        env:
          PROJECT_ID: vgbc-tracker
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
